### ISSUE TITLE
export GOPATH

### ISSUE THREAD

**Issue by capnm** [davecheney/autobench#1]
```
/my/go/autobench/work/go.103/bin/go test -bench=. bench/go1 > /my/go/autobench/work/go1-103.txt
can't load package: package bench/go1: import "bench/go1": cannot find package
make: *** [/my/go/autobench/work/go1-103.txt] Error 1


diff --git a/Makefile b/Makefile
index 98d2dfc..c0aba79 100644
--- a/Makefile
+++ b/Makefile
@@ -10,6 +10,7 @@ GOPATH=$(TOP)
 BENCHCMP=$(GO_TIP_ROOT)/misc/benchcmp

 unexport GOROOT
+export GOPATH

```

**Comment by davecheney** [comment]
Hmm, that is weird, it doesn't break on my machine. If you want to do a pull request i'm happy to give you commit rights as long it fixes the underlying problem.

**Comment by capnm** [comment]
I'm not a make/bash expert, `$ git clone & make` just didn't ran here (ssh ←→ x86_64 Ubuntu 12.04 box).
If it works for you, let's wait if it's broken for the others.

It's going even weirder, do you see this too?

```
BenchmarkBinaryTree17          **2147483647  2147483647**  +17.79%
BenchmarkFannkuch11              2147483647   2147483647  -23.61%

BenchmarkAppend                                 56          176  +214.29%

BenchmarkAppend16Bytes                         648          980  +51.23%
```

**Comment by davecheney** [comment]
I think you are correct that I should export GOPATH, this could be a
difference between various flavors of make. I'll fix it tomorrow morning.

wrt the large numbers, this is an awk problem, awk is limited to 31 bits of
precision, although it correctly calculates the delta. Trust the final
delta % value.

I have a patch to benchcmp that fixes this, i think i cast the number to a
string, i'll try to include that in the autobench src.

**Comment by capnm** [comment]
> I have a patch to benchcmp that fixes this, i think i cast the number to a
> string, i'll try to include that in the autobench src.

Thanks. If the final value is correct, then fixing the human unparsable numbers
is just a cosmetics ;-)

I remember from the dev ML, that you have a RPi. I'm now not able to build the Go release.
The tip is fine. I'm almost sure, the fp coprocessor did somehow work before. No?

```
pkg/go/build
cmd/go
SIGILL: illegal instruction
PC=0x7bfa8

math.init·1()
    /data4/my/go/autobench-capnm/work/go.103/src/pkg/math/pow10.go:34 +0x28
math.init()
    /data4/my/go/autobench-capnm/work/go.103/src/pkg/math/unsafe.go:21 +0x70
strconv.init()
    /data4/my/go/autobench-capnm/work/go.103/src/pkg/strconv/quote.go:441 +0x70
go/parser.init()
    /data4/my/go/autobench-capnm/work/go.103/src/pkg/go/parser/parser.go:2349 +0x78
main.init()
    /data4/my/go/autobench-capnm/work/go.103/src/cmd/go/vet.go:37 +0x78

goroutine 2 [runnable]:
created by runtime.main
    /data4/my/go/autobench-capnm/work/go.103/src/pkg/runtime/proc.c:221

trap    0x6
error   0x0
oldmask 0x0
r0      0x6cb9c0
r1      0x0
r2      0x0
r3      0x0
r4      0x0
r5      0x0
r6      0x0
r7      0x0
r8      0x10837ffc
r9      0x2bdc6c
r10     0x1083c000
fp      0x6cb62a
ip      0x10837ff9
sp      0xb6eace44
lr      0x7c53c
pc      0x7bfa8
cpsr    0x20000010
fault   0x0
```

**Comment by capnm** [comment]
> The tip is fine. I'm almost sure, the fp coprocessor did somehow work before. No?
> Sorry forget it, I found the vfp2/3 patch.
> https://code.google.com/p/go/source/detail?r=bfad57cc7171

**Comment by davecheney** [comment]
I'm going to submit a fix as you suggested for the first issue. This will close this issue, please reopen new issues for the RPi issue and the display issues with benchcmp
