### ISSUE TITLE
ArchLinux compiler issues

### ISSUE THREAD

**Issue by AeroNotix** [davecheney/autobench#10]
Hi,

Since Arch is using GCC 4.8.0 and the release tag of Go contains some undefined behaviour in /src/cmd/cc/funct.c, I am unable to bench on my system without first modifying the build. Perhaps you could add the steps for GCC 4.8+?

**Comment by davecheney** [comment]
What is the exact error message ?

I think this is https://codereview.appspot.com/7665047, if so, I can arrange to patch it into 1.0.3

**Comment by AeroNotix** [comment]
``` shell

/home/xeno/autobench/work/go.103/src/cmd/cc/funct.c:273:13: error: iteration 94u invokes undefined behavior [-Werror=aggressive-loop-optimizations]
   f->sym[o] = S;
             ^
/home/xeno/autobench/work/go.103/src/cmd/cc/funct.c:272:2: note: containing loop
  for(o=0; o<sizeof(f->sym); o++)
  ^
cc1: all warnings being treated as errors
```

Here is the compiler error. Probably I can turn off some checks and get it to compile but I didn't check, yet.

**Comment by davecheney** [comment]
Please rm -rf work/go.103 to ensure that the patch is applied correctly.
