### ISSUE TITLE
The benchmark doesn't work with an ARM VFP2 CPU.

### ISSUE THREAD

**Issue by capnm** [davecheney/autobench#3]
The Go 1.0 release doesn't support the VFP2 coprocessor (RPi).

I did https://code.google.com/p/go/source/detail?r=bfad57cc7171 (Sep 17, 2012)
vs the tip https://code.google.com/p/go/source/detail?r=672069179b80

**Looks great:**
https://github.com/capnm/autobench/blob/master/linux-arm-rpi-capnm.txt

The runtime bench is missing symbols:

```
/data4/my/go/autobench-capnm/work/go.103/bin/go test -test.run=XXX -test.bench=. bench/runtime
# bench/runtime
src/bench/runtime/export_arm_test.go:9: undefined: fadd64
src/bench/runtime/export_arm_test.go:10: undefined: fsub64
src/bench/runtime/export_arm_test.go:11: undefined: fmul64
src/bench/runtime/export_arm_test.go:12: undefined: fdiv64
src/bench/runtime/export_arm_test.go:13: undefined: f64to32
src/bench/runtime/export_arm_test.go:14: undefined: f32to64
src/bench/runtime/export_arm_test.go:15: undefined: fcmp64
src/bench/runtime/export_arm_test.go:16: undefined: fintto64
src/bench/runtime/export_arm_test.go:17: undefined: f64toint
FAIL    bench/runtime [build failed]
```

**Comment by davecheney** [comment]
Hi, Could you please switch to the goarm branch, rm work/go.103, make clean, export GOARM=6 (this is go 1.0 we're talking about here) and try again.

This should reclone 1.0.3, apply a backport of the bits that make the tests pass on the RPi and redo the benchmarks.

**Comment by capnm** [comment]
Thanks Dave, but I think something is wrong.

env|grep GO
GOARM=6
plus your patch applied to go 1.0.3

This looks like a soft fp:
https://raw.github.com/capnm/autobench/15203b64aa26e67ddc660fdf639f77b167f72693/linux-arm-rpi-capnm.txt

**Comment by davecheney** [comment]
I've merged this branch to master, you shouldn't that test file in
src/bench/runtime anymore.

**Comment by capnm** [comment]
Ok, now on the master branch. Compiled with export GOARM=6
https://github.com/capnm/autobench/commit/b993de5d87ed1e87f22b07b51f2e922d7b1a6025
It roughly matches your pandaboard file, you can cherry pick, if you think it's useful.

This one is go1.0.3 & the tests compiled with GOARM=5
https://github.com/capnm/autobench/commit/433dcfcf1091391b03aad98a6aa615cf5c082275
There are indeed some clear visible differences:

```
benchmark                           old ns/op    new ns/op    delta
goarm6: BenchmarkMandelbrot200         93568200      93294806   -0.29%
goram5: BenchmarkMandelbrot200      18523443000   14986993599  -19.09%
```

**Comment by davecheney** [comment]
Why are you passing GOARM=5 ? Is there a problem or is this just an
experiment ?

On my A15 powered chromebook there is very little difference in the
madelbrot benchmark because it is 100% FPU bound

**Comment by capnm** [comment]
Yes, only an experiment to see if or how much something changes
(and to be sure, that the vfp2 backport works ;)

Impressive numbers. Thanks for making Go usable on ARM.

**Comment by davecheney** [comment]
If you want to send me a pull request with your benchmark numbers, i'm
happy to add them to the dataset.
